apiVersion: v1
kind: Service
metadata:
  name: {{ include "belabox-receiver.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "belabox-receiver.name" . }}
  ports:
  - name: srtla
    port: 5000
    protocol: UDP
    targetPort: srtla
    nodePort: {{ .Values.service.nodePorts.srtla }}
{{- if .Values.service.nodePorts.tcp8181 }}
  - name: stats
    port: 8181
    protocol: TCP
    targetPort: stats
    nodePort: {{ .Values.service.nodePorts.stats }}
{{- end }}
  - name: srt
    port: 8282
    protocol: UDP
    targetPort: srt
    nodePort: {{ .Values.service.nodePorts.srt }}
