---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-lgsm-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.lgsmConfig.size }}

{{- if .Values.persistence.serverFiles.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-server-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.serverFiles.size }}
{{- end }}

{{- if .Values.persistence.log.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.log.size }}
{{- end }}

{{- if .Values.persistence.backups.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "7dtd.fullname" . }}-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}
