apiVersion: v1
kind: Service
metadata:
  name: {{ include "7dtd.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "7dtd.name" . }}
  ports:
    - name: gameporta
      port: 26900
      targetPort: gameporta
      protocol: UDP
      nodePort: {{ .Values.service.ports.gamePortA }}
    - name: gameportb
      port: 26900
      targetPort: gameportb
      protocol: TCP
      nodePort: {{ .Values.service.ports.gamePortB }}
    - name: gameportc
      port: 26901
      targetPort: gameportc
      protocol: UDP
      nodePort: {{ .Values.service.ports.gamePortC }}
    - name: gameportd
      port: 26902
      targetPort: gameportd
      protocol: UDP
      nodePort: {{ .Values.service.ports.gamePortD }}
    - name: serverfixes
      port: 8082
      targetPort: serverfixes
      {{- if .Values.service.ports.serverfixes }}
      nodePort: {{ .Values.service.ports.serverfixes }}
      {{- end }}
    - name: telnet
      port: 8081
      targetPort: 8081
      protocol: TCP
      {{- if .Values.service.ports.telnet }}
      nodePort: {{ .Values.service.ports.telnet }}
      {{- end }}
    - name: webadmin
      port: 8080
      targetPort: 8080
      protocol: TCP
      {{- if .Values.service.ports.webadmin }}
      nodePort: {{ .Values.service.ports.webadmin }}
      {{- end }}
