apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak3.fullname" . }}
  labels:
    {{- include "teamspeak3.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.voice.port }}
      targetPort: voice
      protocol: UDP
      name: voice
      nodePort: {{ .Values.service.voice.nodePort }}
    - port: {{ .Values.service.fileTransfer.port }}
      targetPort: file-transfer
      protocol: TCP
      name: file-transfer
      nodePort: {{ .Values.service.fileTransfer.nodePort }}
    # Important: We do not expose the serverQuery port as a NodePort for security reasons
    # This service is only being used for liveness/readiness probes
  selector:
    {{- include "teamspeak3.selectorLabels" . | nindent 4 }}
