image:
  repository: vinanrra/7dtd-server
  tag: v0.7.10
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    gamePortA: 30100
    gamePortB: 30100
    gamePortC: 30101
    gamePortD: 30102
    # serverfixes: 30105
    # telnet: 30104
    # webadmin: 30103

env:
  LINUXGSM_VERSION: v24.3.4
  START_MODE: "1"
  VERSION: stable
  PUID: "1000"
  PGID: "1000"
  TimeZone: Europe/Berlin
  TEST_ALERT: "NO"
  UPDATE_MODS: "NO"
  MODS_URLS: ""
  ALLOC_FIXES: "NO"
  ALLOC_FIXES_UPDATE: "NO"
  UNDEAD_LEGACY: "NO"
  UNDEAD_LEGACY_VERSION: stable
  UNDEAD_LEGACY_UPDATE: "NO"
  DARKNESS_FALLS: "NO"
  DARKNESS_FALLS_UPDATE: "NO"
  DARKNESS_FALLS_URL: "False"
  CPM: "NO"
  CPM_UPDATE: "NO"
  BEPINEX: "NO"
  BEPINEX_UPDATE: "NO"
  BACKUP: "NO"
  BACKUP_HOUR: "5"
  BACKUP_MAX: "7"
  MONITOR: "NO"

persistence:
  data:
    size: 20Gi
  lgsmConfig:
    size: 1Gi
  serverFiles:
    enabled: true
    size: 20Gi
  log:
    enabled: false
    size: 2Gi
  backups:
    enabled: false
    size: 5Gi
